---
- name: start apache
  service: name={{ item.apache_daemon }} state=started
  when: ansible_os_family == '{{ item.os }}'
  with_items:
    - { os: Debian, apache_daemon: apache2 }
    - { os: RedHat, apache_daemon: httpd }

- name: stop apache
  service: name={{ item.apache_daemon }} state=stopped
  when: ansible_os_family == '{{ item.os }}'
  with_items:
    - { os: Debian, apache_daemon: apache2 }
    - { os: RedHat, apache_daemon: httpd }

- name: restart apache
  service: name={{ item.apache_daemon }} state=restarted
  when: ansible_os_family == '{{ item.os }}'
  with_items:
    - { os: Debian, apache_daemon: apache2 }
    - { os: RedHat, apache_daemon: httpd }
