---
- name: Install Apache2 server (Debian)
  tags: apache
  apt: name=apache2 state=latest
  when: ansible_os_family == 'Debian'

- name: Install Apache 2 server (RedHat)
  tags: apache
  yum: name=httpd state=latest
  when: ansible_os_family == 'RedHat'
